name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: avery519314
          password: dckr_pat_eKw1syoel_-cTTW6FBUq5Hj62Mw
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: avery519314/clockbox:latest
      - name: Build Docker Image
      
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |-
         gcloud auth configure-docker --quiet
         gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Push Docker Image to Container Registry (GCR)
      
        env:
         GIT_TAG: v1
         run: |-
          docker tag $IMAGE_NAME:latest gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:latest
          docker push gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:$GIT_TAG

      - name: Push Docker Image to Artifact Registry 
    env:
        GIT_TAG: v1
        run: |-
         docker tag $IMAGE_NAME:$GIT_TAG us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/$IMAGE_NAME:$GIT_TAG
         docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/$IMAGE_NAME:$GIT_TAG
          

