name: python-docker-example
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: python-docker-dev-example
      PROJECT_ID: gcp-demo-project-413710
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t python-docker-dev-example:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: v1
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/${{ env.PROJECT_ID }}/python-docker-dev-example:latest
        docker tag $IMAGE_NAME:latest gcr.io/${{ env.PROJECT_ID }}/python-docker-dev-example:$GIT_TAG
        docker push gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:latest
        docker push gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:$GIT_TAG

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v1
      run: |-
        docker tag $IMAGE_NAME:$GIT_TAG us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/python-docker-dev-example:$GIT_TAG
        docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/images/python-docker-dev-example:$GIT_TAG

